# Generated by Django 5.2.4 on 2025-11-20 18:49

import api.services.storages
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_address_company_document_email_person_patient_doctor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file',
            field=models.FileField(default=None, storage=api.services.storages.MediaStorage(), upload_to='person_docs/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='document',
            name='uploaded_at',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='person',
            name='fileserver_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='party',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.party'),
        ),
    ]
