# Generated by Django 5.2.4 on 2025-11-21 19:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_document_file_document_uploaded_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='fullname',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
