# Generated by Django 5.2.4 on 2025-11-21 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_person_fullname'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='party',
            name='email',
        ),
        migrations.RemoveField(
            model_name='party',
            name='name',
        ),
    ]
