# Generated by Django 5.2.4 on 2025-11-22 11:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_remove_party_email_remove_party_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='person',
            name='party',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, to='api.party'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='phone',
            name='party',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='api.party'),
        ),
    ]
