# Generated by Django 5.2.4 on 2025-11-22 21:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_person_user_alter_person_party_alter_phone_party'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
