# Generated by Django 5.2.4 on 2025-11-23 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_clinicalnote_patientrecord'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PatientSandbox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('symptoms', models.JSONField(blank=True, null=True)),
                ('vitals', models.JSONField(blank=True, null=True)),
                ('calculators', models.JSONField(blank=True, null=True)),
                ('genomic', models.JSONField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('patient', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
