# Generated by Django 5.2.4 on 2025-11-23 19:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_patientsandbox'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientsandbox',
            name='patient',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.patient'),
        ),
    ]
