# Generated by Django 5.2.4 on 2025-11-23 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_patientsandbox_patient'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='patients',
            field=models.ManyToManyField(blank=True, related_name='doctors', to='api.patient'),
        ),
    ]
